site_name: RISM Online Documentation
site_url: https://rism.online/docs/
exclude_docs: |
  generate_route_docs.py
nav:
  - Home: index.md
  - API:
      - "Using the API": api/api.md
      - "The Search API": api/search-api.md
      - "Incipit Search": api/incipit-search.md
      - "The Resource API": api/resource-api.md
      - "Routes": api/routes.md
      - "Search options by Mode": api/modes.md
      - "Multilingual Support": api/languages.md
  - "Reconciliation Service":
      - "Introduction": reconciliation/introduction.md
      - "The RISM Online Reconciliation Service": reconciliation/service.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    scheme: rism
extra_css:
  - stylesheets/extra.css